### PR TITLE
Added profile directory for org homepage

### PR DESCRIPTION
**Pull request by mw-kapilg**
A few more suggestions for the text:

- You can find the content that was on this page now located here.
- This page no longer contains the content you are looking for; it has been moved to this new location.
- We've moved the content that was here to this new page for easier access.
- The information once displayed on this page is now available at this new location.

### CODE REVIEW

**Comment by mcafaro** [comment]
Check this out: https://stackoverflow.com/questions/65485553/can-a-github-readme-be-redirected-to-another-location

> However, if your README is a symlink to a file in another directory and otherwise named appropriately, GitHub will follow the symlink when it renders the page, provided the path is relative to your repository.

This might be worth trying.

**Comment by mw-hrastega** [comment]
> * You can find the content that was on this page now located here.
> * This page no longer contains the content you are looking for; it has been moved to this new location.
> * We've moved the content that was here to this new page for easier access.
> * The information once displayed on this page is now available at this new location.

Hi Kapil,

1) I have contacted our editor regarding the redirect message. I can approve the pull request when I hear back from her.
2) If the redirection can take place automatically (as Mark suggests), then we can get rid of an extra message and click, which will be great. 
3) Once the URL is finalized, please inform me, so I can update the link here: https://www.mathworks.com/help/matlab/matlab_prog/continuous-integration-with-matlab-on-ci-platforms.html#mw_6cb5114e-198f-48b2-9d94-e1efd7bf653c

Thanks,
Houman

**Comment by mcafaro** [comment]
> 3. Once the URL is finalized, please inform me, so I can update the link here: https://www.mathworks.com/help/matlab/matlab_prog/continuous-integration-with-matlab-on-ci-platforms.html#mw_6cb5114e-198f-48b2-9d94-e1efd7bf653c

I think we should just link to https://github.com/matlab-actions now because it will contain the overview and will mitigate against similar challenges in the future.

**Comment by mw-hrastega** [comment]
Here are some suggested messages in case the redirection cannot take place automatically:

-This content has been moved. You can find it here: <URL>
-This page has been moved to <URL>.
-We've moved this content to <URL>.

**Comment by acampbel** [comment]
> Check this out: https://stackoverflow.com/questions/65485553/can-a-github-readme-be-redirected-to-another-location
> 
> > However, if your README is a symlink to a file in another directory and otherwise named appropriately, GitHub will follow the symlink when it renders the page, provided the path is relative to your repository.
> 
> This might be worth trying.

This works pretty seamlessly, I tested it out here

https://github.com/acampbel/parfor/

**Comment by mcafaro** [comment]
> This works pretty seamlessly, I tested it out here
> 
> https://github.com/acampbel/parfor/

It seems to work only when looking at the README from the repository page. But not if you link directly to the README.md file, which I think is what we are trying to account for?: https://github.com/acampbel/parfor/blob/main/README.md

**Comment by acampbel** [comment]
> > This works pretty seamlessly, I tested it out here
> > https://github.com/acampbel/parfor/
> 
> It seems to work only when looking at the README from the repository page. But not if you link directly to the README.md file, which I think is what we are trying to account for?: https://github.com/acampbel/parfor/blob/main/README.md

I dont think we need to account for that. My understanding is we are trying to account for people bookmarking the repo, not the actual file in the repo

**Pull request merged**
